### PR TITLE
Create Letter Combinations of a Phone Number

### PR DESCRIPTION
**Pull request by jainss**
Create Letter Combinations of a Phone Number

Write a  code in java.

## Make a new file with name Create Letter Combinations of a Phone Number and write a program 

issue :- combination of phone Number problem (leetcode) Medium 
issue number #313

### CODE REVIEW

**Comment by jainss** [comment]
Please merge this 👀

**Comment by kanak22** [comment]
Link the issue in description

**Comment by jainss** [comment]
Where ?

**Comment by kanak22** [comment]
Every issue have a number after its title, something like #(some number)

so in your PR in the description box where this is written

issue :- combination of phone Number problem (leetcode) Medium

here add the issue number

**Comment by jainss** [comment]
Now it ok? 
actually i am not good at open source 😪

**Review by kanak22 — CHANGES_REQUESTED** [review]
1. Make a folder with the name of the question and then add this codefile in that folder inside leetcode folder
2. Add comments in you code

**Comment by kanak22** [comment]
Don't worry you will be ;)

**Review by jainss — COMMENTED** [review]
Now i have done this change please see this  once

**Comment by jainss** [comment]
please see this and if any error please tell

**Comment by kanak22** [comment]
You forgot the folder.. add the folder as well

**Comment by jainss** [comment]
Now i did this please check one more time 🥱😢

**Comment by kanak22** [comment]
Folder is still not there :(

**Comment by jainss** [comment]
Bro i'm done 🥱😢

**Comment by kanak22** [comment]
Okay then I am closing it

**Comment by jainss** [comment]
ok thanks 👍

**Pull request closed without merging**
