### PR TITLE
Create Merge Sorted Array.c

### PR DESCRIPTION
**Pull request by Navaneethp007**
## Related Issue 

- Solve the problem given in LeetCode of merging 2 given arrays and sorting them in ascending order (non-decreasing order) in C language.

Closes: #574 

## Describe the changes you've made

I have written a code in c  (only the function) for the above problem. The sorted array is stored in nums1 array. 

## Mention any unusual behavior of your code (Write NA if not)
Any unusual behavior of your code: NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
@Navaneethp007 Add it in the correct folder

**Comment by Navaneethp007** [comment]
ok

**Comment by Navaneethp007** [comment]
I have done it

**Comment by Navaneethp007** [comment]
I have done the necessary changes. But I think I might have done the
changes twice due to my network issues. If so, sorry about the
inconvenience.

**Pull request closed without merging**
