### PR TITLE
[Leetcode] Unique Binary Search Trees II

### PR DESCRIPTION
**Pull request by shalyavarnika**
## Related Issue 

- Given an integer n, return all the structurally unique BST's (binary search trees), which has exactly n nodes of unique values from 1 to n. Return the answer in any order.

Closes: #113 

## 

Added code in C++ language.

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by shalyavarnika** [comment]
My pull requests were all merging into one that is why I have narrowed it down to one program. Please accept it so that I can create new pull request.

**Review by kanak22 — CHANGES_REQUESTED** [review]
rename the codefile and folder with the same name as that of the question

**Comment by shalyavarnika** [comment]
@kanak22 updated

**Review by shalyavarnika — COMMENTED** [review]
updated

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
