### PR TITLE
[Leetcode] Binary Tree Zigzag Level Order Traversal

### PR DESCRIPTION
**Pull request by shalyavarnika**
## Related Issue 

- Given the root of a binary tree, return the zigzag level order traversal of its nodes' values. (i.e., from left to right, then right to left for the next level and alternate between).

Closes: #116

## Describe the changes you've made

Added the code in C++ language

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by kanak22 — CHANGES_REQUESTED** [review]
Add comments to your code

**Comment by shalyavarnika** [comment]
@kanak22  Added comments

**Comment by shalyavarnika** [comment]
@kanak22 Please review this.

**Comment by shalyavarnika** [comment]
@kanak22 Hey.. I have added proper comments and changed the name of the file as mentioned. Please review.

**Comment by kanak22** [comment]
@shalyavarnika I was busy with other stuffs dont get panicked I am reviewing ;)

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
