### PR TITLE
Added code for Remove Duplicate Letters - Leetcode Problem

### PR DESCRIPTION
**Pull request by neenad99**
## Related Issue 

- Added code for remove duplicate letters leetcode problem 316

Closes: [#83](https://github.com/kanak22/CP-DSA-Questions/issues/83)

## Describe the changes you've made

Added solution.cpp file to LeetCode/Remove_Duplicate_Letters folder and updated LeetCode/LeetCode.md file

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Review by kanak22 — COMMENTED** [review]
1. Replace _ with spaces in folder name
2. Rename codefile from solution to Remove Duplicate Letters

**Review by kanak22 — CHANGES_REQUESTED** [review]
Replace _ with spaces in folder name
Rename codefile from solution to Remove Duplicate Letters

**Review by kanak22 — APPROVED** [review]

**Comment by kanak22** [comment]
Resolve merge conflicts by pulling the changes

**Comment by neenad99** [comment]
resolved merge conflicts @kanak22  please check

**Pull request merged**
