### PR TITLE
[Leetcode] Lowest Common Ancestor

### PR DESCRIPTION
**Pull request by shalyavarnika**
## Related Issue 

- Info about the related issue 

Closes: #114 

## Describe the changes you've made

I have added a simple code for Lowest Common Ancestor.

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by kanak22 — CHANGES_REQUESTED** [review]
name the codefile exactly as the folder

**Comment by kanak22** [comment]
resolve the conflicts

**Review by kanak22 — APPROVED** [review]

**Comment by kanak22** [comment]
Hey @shalyavarnika, Resolve the conflicts by pulling the changes

**Comment by shalyavarnika** [comment]
@kanak22 resolved

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
