### PR TITLE
added first bad version code

### PR DESCRIPTION
**Pull request by rustzz-27**
Closes: #101 

## Describe the changes you've made
Added a new folder inside Leetcode named "First Bad version" and added a c++ file and a readme file that contains question description and sample input-output.

## Mention any unusual behaviour of your code (Write NA if not)
NA
## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by rustzz-27** [comment]
Pls review my pr 
issue #101

**Review by kanak22 — CHANGES_REQUESTED** [review]
hey @rustzz-27 I really appreciate your efforts but kindly do these

1. take the content of the readme you added, paste it into the codefile and comment it out. 
2. rename the codefile from solution to the name of the question.

**Comment by rustzz-27** [comment]
> hey @rustzz-27 I really appreciate your efforts but kindly do these
> 
> 1. take the content of the readme you added, paste it into the codefile and comment it out.
> 2. rename the codefile from solution to the name of the question.

Hello, I have made the suggested changes pls review

**Review by kanak22 — APPROVED** [review]

**Comment by rustzz-27** [comment]
hello i have a doubt

**Comment by kanak22** [comment]
https://stackoverflow.com/questions/15691611/how-do-i-pull-changes-from-github-repository-to-my-local-machine

refer to this

**Pull request merged**
