### PR TITLE
I have done the code in python. kindly merge it. if any conflicts let me know.

### PR DESCRIPTION
**Pull request by satyam-mahajan**
## Related Issue 

- Info about the related issue 

Closes: #255

## Describe the changes you've made

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
link the issue in description of the PR

**Comment by satyam-mahajan** [comment]
@kanak22 please help me ,how to link in description of the PR.

**Review by kanak22 — CHANGES_REQUESTED** [review]
@satyam-mahajan just rename the files as Rotting Oranges.py and Integer To Roman.py

**Review by kanak22 — APPROVED** [review]

**Comment by kanak22** [comment]
@satyam-mahajan  rename interger to roman as well

**Comment by kanak22** [comment]
Integer To Roman.py

change to just this

**Comment by satyam-mahajan** [comment]
I change in my fork, should I submit the pull request again?

**Comment by kanak22** [comment]
The name of the file is Inter To Roman.py change this 'Inter' to Integer so that it will be like

Integer To Roman.py

**Comment by satyam-mahajan** [comment]
I change inter to integer in my fork.

**Review by kanak22 — APPROVED** [review]

**Comment by satyam-mahajan** [comment]
How to merge, can you help?

**Pull request merged**
