### PR TITLE
[Leetcode] Flatten Binary Tree to Linked List

### PR DESCRIPTION
**Pull request by shalyavarnika**
## Related Issue 

-Given the root of a binary tree, flatten the tree into a "linked list":

The "linked list" should use the same TreeNode class where the right child pointer points to the next node in the list and the left child pointer is always null.
The "linked list" should be in the same order as a pre-order traversal of the binary tree.

Closes: #115 

## Describe the changes you've made

Added the code in C++ language

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by kanak22 — CHANGES_REQUESTED** [review]
Rename the codefile same as the name of the folder and add comments in code

**Comment by shalyavarnika** [comment]
@kanak22  Added comments and changed the file name

**Comment by shalyavarnika** [comment]
@kanak22  Please review this.

**Comment by shalyavarnika** [comment]
@kanak22 Hi, I have added proper comments. Please review.

**Review by kanak22 — APPROVED** [review]
The file name should have spaces 

rename it to Flatten Binary Tree to Linked List from the current one ;)

**Review by kanak22 — CHANGES_REQUESTED** [review]
The file name should have spaces

rename it to Flatten Binary Tree to Linked List from the current one ;)

**Comment by kanak22** [comment]
Do this asap and i will be merging it ;) sorry for that approved one ... will approve this once you rename it.

**Comment by shalyavarnika** [comment]
@kanak22 Done

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
