### PR TITLE
Leetcode question on binary search in 2d array added

### PR DESCRIPTION
**Pull request by Devansh-gaur-1611**
I have added 2 question on binary search in 2d array in which the arrays are sorted strictly and sorted row-column wise

### CODE REVIEW

**Comment by kanak22** [comment]
Do you have an issue opened regarding this PR?

**Comment by Devansh-gaur-1611** [comment]
hello @kanak22, sorry but I haven't opened an issue. Actually, by mistake, I have only read half of the contribution.md. So I just thought that we just have to create pr of solutions to questions.
Can u plz help me by telling me what I have to do now, please? Also, again I am sorry for my mistake.

**Comment by kanak22** [comment]
@Devansh-gaur-1611 then do give a read to contributing.md and open an issue first, get it assigned and then make a PR. :)

Regarding this PR, I will be closing it since it do not follow the guidelines of the project.

**Comment by kanak22** [comment]
For any further queries you can join the discord server and ask :)

**Pull request closed without merging**
