### PR TITLE
Add solution to Merge k sorted list(cpp)

### PR DESCRIPTION
**Pull request by arp99**
## Related Issue 

- Info about the related issue 

Closes: #217 

## Describe the changes you've made

Added solution to Merge K sorted list in Cpp

## Mention any unusual behaviour of your code (Write NA if not)
NA
## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Problem details
>You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.
Merge all the linked-lists into one sorted linked-list and return it.  
Input: lists = [[1,4,5],[1,3,4],[2,6]]
Output: [1,1,2,3,4,4,5,6]
Explanation: The linked-lists are:
[
  1->4->5,
  1->3->4,
  2->6
]
merging them into one sorted list:
1->1->2->3->4->4->5->6

### CODE REVIEW

**Comment by arp99** [comment]
@kanak22 Please review it 😅

**Comment by arp99** [comment]
@kanak22 I know it is a difficult task to review PRs, I just wanted to confirm if you missed my PR 😊

**Comment by kanak22** [comment]
Hey @arp99 I will be reviewing every PR and issue in evening today... Stuck in some work for now ... 🥺

**Comment by arp99** [comment]
> Hey @arp99 I will be reviewing every PR and issue in evening today... Stuck in some work for now ... 🥺

Ok take your time no problem, just wanted to confirm you might be in some problem

**Review by kanak22 — CHANGES_REQUESTED** [review]
Replace _ with spaces in the names of folder and codefile asap ;)

**Comment by arp99** [comment]
> Replace _ with spaces in the names of folder and codefile asap ;)

Ok

**Comment by arp99** [comment]
> Replace _ with spaces in the names of folder and codefile asap ;)

Done with the changes please review @kanak22

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
