### PR TITLE
Added code for Maximum Subarray

### PR DESCRIPTION
**Pull request by dsasaank-369**
## Related Issue 

- Info about the related issue 

Closes: #120

## Describe the changes you've made

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
Link the issue in PR

**Comment by dsasaank-369** [comment]
Can I know whether my pull request was accepted?

**Comment by kanak22** [comment]
@dsasaank-369 Your PR isnt accepted yet. Kindly link the issue in the description of the PR

**Comment by dsasaank-369** [comment]
I am new to GitHub can i know how can I do that

**Comment by kanak22** [comment]
In the description box this PR there is a section of 

Related Issue
Info about the related issue
Closes: #[issue number that will be closed through this PR]

edit this with the issue number 

Related Issue
Info about the related issue
Closes: #120

**Review by kanak22 — CHANGES_REQUESTED** [review]
@dsasaank-369 

1. delete the content of the readme you edited in arrays in 450 DSA
2.  add the code inside a file named Maximum Subarray
3. plcae this codefile inside the Maximum Subaray folder in leetcode folder

**Comment by dsasaank-369** [comment]
Followed all the steps mentioned, please verify it

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
