### PR TITLE
Integer to Roman in Java

### PR DESCRIPTION
**Pull request by kshitijver**
## Related Issue 

Solution of Leetcode\Integer_To_Roman in Java.

Closes: #255

## Describe the changes you've made

I gave a solution to this problem in java which is accepted on leetcode.

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by kanak22 — CHANGES_REQUESTED** [review]
Rename the codefile exactly as the folder and add comments in the loop asap ;)

**Comment by kshitijver** [comment]
Added proper comments and renamed file.

**Review by kanak22 — CHANGES_REQUESTED** [review]
replace _ with spaces

the codefile should be named as Integer To Roman.java

**Comment by kshitijver** [comment]
Renamed to Integer To Roman.java

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
