### PR TITLE
Solution of Jzzhu and Sequences problem

### PR DESCRIPTION
**Pull request by DavidMaged171**
Added comments

### CODE REVIEW

**Comment by DavidMaged171** [comment]
Accept this PR ,Please.

**Review by kanak22 — CHANGES_REQUESTED** [review]
Add the file in the folder nd rename the codefile to Jzzhu and Sequence.cpp

nd i will merge it asap

**Comment by DavidMaged171** [comment]
Where is folder nd?

**Comment by kanak22** [comment]
You have to create a folder with the name of the question inside he rating 1300 folder

**Review by kanak22 — APPROVED** [review]

**Comment by DavidMaged171** [comment]
Thanks a lot

**Pull request merged**
