### PR TITLE
1468N - Waste Sorting

### PR DESCRIPTION
**Pull request by samarthraj11**
## Related Issue 

- Info about the related issue 

Closes: #5 

Added the solution for Waste Sorting in C++.

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
Hey @samarthraj11, everything is fine. Just comment your code after that it will be merged ;)

**Comment by samarthraj11** [comment]
I am not sure I understand   comment the code means. Sorry , can u please explain.

**Comment by kanak22** [comment]
it means that add comments in your code so that other people who will refer to this for solution of that question, can understand what is actually happening in the code

**Comment by samarthraj11** [comment]
Okay got it. Thanks

**Comment by kanak22** [comment]
welcome ;)

**Comment by samarthraj11** [comment]
hi @kanak22, please review and suggest and any other changes if required.

**Comment by kanak22** [comment]
;)

**Review by kanak22 — COMMENTED** [review]
Its good

**Pull request merged**
