### PR TITLE
Added the code for leetcode largest rectangle in histogram 

### PR DESCRIPTION
**Pull request by 19-ade**
## Related Issue 

- Info about the related issue 

Closes: #17 

## Describe the changes you've made

Added the solution in the Leetcode directory and added the question in the readme.md 

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA
## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
Kindly link the related issue.

**Comment by 19-ade** [comment]
> Kindly link the related issue.

Made the changes in the template . Sorry for not mentioning it before

**Comment by kanak22** [comment]
Hey @19-ade Make a directory and then add that code file into it.

**Comment by 19-ade** [comment]
Ill send another PR with a renewed folder. Sorry for the inconvenience.

**Pull request closed without merging**
