### PR TITLE
450 dsa

### PR DESCRIPTION
**Pull request by cp-Coder**
## Related Issue 

- Info about the related issue 

Closes: #52

## Describe the changes you've made
Added Knapsack Solution (C++) in 450 DSA/Dynamic Programming folder in the repository

## Mention any unusual behaviour of your code (Write NA if not)
NA
## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by Nirbhay1910** [comment]
That's not good bro! I wanted to work on this question that's why I raised this issue :(

**Comment by Nirbhay1910** [comment]
And I think we must wait for the issue to be assigned right?  Or we can make PRs without assigning?

**Comment by kanak22** [comment]
no PRs will be entertained without the issue being assigned .. dont worry @Nirbhay1910

**Comment by cp-Coder** [comment]
Sorry here also. I won't interfere next time.

**Pull request closed without merging**
