### PR TITLE
Update 791A Bear and Big Brother.cpp

### PR DESCRIPTION
**Pull request by ruturaj-gh**
i just make the code more descriptive for the user

## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

## Describe the changes you've made

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Comment by kanak22** [comment]
This PR is for????

**Comment by ruturaj-gh** [comment]
> This PR is for????

Just wanted to contribute for hactoberfest
That's why i landed here
If you don't liked it i'll close
Happy open-source : )

**Comment by kanak22** [comment]
@ruturaj-gh Contributing is good but you should read the guidelines of the project in which you wish to contribute. I hope you won't be doing this to every second repository just for getting swags in hacktoberfest. Kindly have some respect towards open-source repositories :)

**Comment by ruturaj-gh** [comment]
> @ruturaj-gh Contributing is good but you should read the guidelines of the project in which you wish to contribute. I hope you won't be doing this to every second repository just for getting swags in hacktoberfest. Kindly have some respect towards open-source repositories :)

Im kindly sorry if i have done something wrong coz new to this github and all maybe it will take some time understand things

**Comment by kanak22** [comment]
its okay :)

**Pull request closed without merging**
