### PR TITLE
[Leetcode] Minimum Absolute Difference in BST

### PR DESCRIPTION
**Pull request by shalyavarnika**
## Related Issue 

- Given the root of a Binary Search Tree (BST), return the minimum absolute difference between the values of any two different nodes in the tree.

Closes: #112 

## Describe the changes you've made

I have added the code for the following question.
https://leetcode.com/problems/minimum-absolute-difference-in-bst/

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

### CODE REVIEW

**Review by kanak22 — APPROVED** [review]

**Comment by kanak22** [comment]
resolve merge conflicts

**Comment by shalyavarnika** [comment]
@kanak22 resolved

**Comment by kanak22** [comment]
Resolve merge conflicts by pulling the changes

**Comment by shalyavarnika** [comment]
@kanak22 I have pulled the changes and resolved the conflicts

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
