### PR TITLE
added delete_and_earn sol.cpp and updated leetcode.md

### PR DESCRIPTION
**Pull request by rachana-singh27**
## Related Issue 

- Issue - To Solve Delete and Earn [Leetcode Problem] in C++ 

Closes: #82 

## Describe the changes you've made

-made folder with question name under leetcode
-added c++ solution in the file delete_and_earn.cpp
-Explained approach of the problem, added comments to make the code clear and mentioned Time and Space complexities.

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Please review it @kanak22 and let me know in case of changes, thanks :)

### CODE REVIEW

**Review by kanak22 — COMMENTED** [review]
Remove the dash from folder and codefile name

**Comment by kanak22** [comment]
and resolve the conflicts

**Comment by rachana-singh27** [comment]
> Remove the dash from folder and codefile name

Done!

**Comment by rachana-singh27** [comment]
> and resolve the conflicts

Done!

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
