### PR TITLE
Added basic structure for selection of language

### PR DESCRIPTION
**Pull request by vipul-2003**
Added selection of language option  and provided  assigning comment

## Related Issue 

- Info about the related issue 

Closes: #[issue number that will be closed through this PR]

## Describe the changes you've made

Give a clear description what modifications you have made

## Mention any unusual behaviour of your code (Write NA if not)

##NA 

## Checklist:

(To mark, write x inside the square brackets like this: [x])

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
Any additional information you want to give

`CREATED BASIC STRUCTURE FOR THE COMMITS  AND PROVIDED OPTIONS FOR THE SELECTION OF LANGUAGES `

### CODE REVIEW

**Comment by vipul-2003** [comment]
Review the pull request

**Comment by kanak22** [comment]
Who asked for this?

**Comment by vipul-2003** [comment]
> Who asked for this?

No one but  i think may be good ..?

**Comment by kanak22** [comment]
@vipul-2003 firstly you just spammed the issue section, the project guidelines are that any contributor can't open more than one issue at a time.

then you kept pinging two other contributors for assignment.. and now u made a PR which wasnt required at all. 

I m sorry but this is misbehaving and i wont be considering any of your issues and this PR. Hence, I am closing all of them

**Comment by kanak22** [comment]
If you wish to contribute, read the guidelines, join the discord for instructions and then try to contribute.

**Pull request closed without merging**
