### PR TITLE
Matrix Diagonal Sum - LeetCode

### PR DESCRIPTION
**Pull request by silicolicious**
## Related Issue 
 
Fixes: #9  

Closes: #9 

## Describe the changes you've made

I have added the solution to the question *Matrix Diagonal Sum* of LeetCode along with proper comments explaining the code.

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

## Additional Info (optional)
I would like hacktoberfest-accepted label to be added for this PR.

Thank you!

### CODE REVIEW

**Comment by silicolicious** [comment]
@kanak22 Please review it and merge my PR.
Let me know if there is any problem which needs to be rectified.

**Comment by kanak22** [comment]
Hey, @silicolicious  Just remove the question.md else everything is right .. let me know when its done ;)

**Review by kanak22 — CHANGES_REQUESTED** [review]
Remove question.md

**Comment by silicolicious** [comment]
@kanak22 I have deleted the question.md file. Done.

**Review by kanak22 — APPROVED** [review]

**Pull request merged**
